feat: allow comments by removing them
php-coder/query2app pull request #22
Opened 2022-10-05 14:24 UTC by kirsanium

2022-10-06 03:32 UTC, php-coder commented
Сходу не заработало:
```console
diff --git examples/js/endpoints.yaml examples/js/endpoints.yaml
index 7d1d09a..163f902 100644
--- examples/js/endpoints.yaml
+++ examples/js/endpoints.yaml
@@ -18,6 +18,7 @@
 - path: /v1/collections/:collectionId/categories/count
   get:
     query: >-
+      -- SQL comments can be used but they won't be included in the resulted code
       SELECT COUNT(DISTINCT s.category_id) AS counter
         FROM collections_series cs
         JOIN series s
diff --git examples/js/routes.js examples/js/routes.js
index a6d39a3..043cf40 100644
--- examples/js/routes.js
+++ examples/js/routes.js
@@ -19,7 +19,7 @@ app.get('/v1/categories/count', (req, res) => {

 app.get('/v1/collections/:collectionId/categories/count', (req, res) => {
     pool.query(
-        'SELECT COUNT(DISTINCT s.category_id) AS counter FROM collections_series cs JOIN series s ON s.id = cs.series_id WHERE cs.collection_id = :collectionId',
+        '  FROM collections_series cs JOIN series s ON s.id = cs.series_id WHERE cs.collection_id = :collectionId',
         { "collectionId": req.params.collectionId },
         (err, rows, fields) => {
             if (err) {
diff --git examples/python/routes.py examples/python/routes.py
index 2035404..d36a06d 100644
--- examples/python/routes.py
+++ examples/python/routes.py
@@ -51,7 +51,7 @@ def get_v1_collections_collection_id_categories_count(collectionId, conn = Depen
     try:
         with conn:
             with conn.cursor(cursor_factory = psycopg2.extras.RealDictCursor) as cur:
-                cur.execute("SELECT COUNT(DISTINCT s.category_id) AS counter FROM collections_series cs JOIN series s ON s.id = cs.series_id WHERE cs.collection_id = %(collectionId)s", { "collectionId": collectionId })
+                cur.execute("  FROM collections_series cs JOIN series s ON s.id = cs.series_id WHERE cs.collection_id = %(collectionId)s", { "collectionId": collectionId })
                 result = cur.fetchone()
                 if result is None:
                     raise HTTPException(status_code=404)
```

2022-10-06 03:43 UTC, php-coder commented
Проблема проявляется когда комментарий указан в начале, перед SQL-запросом -- почему-то после нее не добавляется перевод строки. Ок, тогда пока, оставляю PR открытым.

2022-10-07 10:18 UTC, php-coder commented on examples/js/endpoints.yaml
> +      WHERE cs.collection_id = :p.collectionId
Зачем это изменение?

2022-10-07 10:18 UTC, php-coder commented on examples/js/endpoints.yaml
> +    query: |-
Зачем везде менять было?

2022-10-07 10:20 UTC, php-coder requested changes
Не надо править то, что не сломалось :)

2022-10-07 10:24 UTC, kirsanium commented on examples/js/endpoints.yaml
> +    query: |-
Для наглядности, чтобы уменьшить шанс того, что кому-то придет в голову использовать `>-` с комментариями :)

2022-10-10 03:25 UTC, merged